// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjH-MgvnNyjOWAZbtK39NIDiJTby0vJrc',
    appId: '1:318003575454:web:b5f8a21694420957a4598f',
    messagingSenderId: '318003575454',
    projectId: 'tipsyapp-c8bff',
    authDomain: 'tipsyapp-c8bff.firebaseapp.com',
    storageBucket: 'tipsyapp-c8bff.firebasestorage.app',
    measurementId: 'G-1ZEQ34C0J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAglCtpzZNidx5W4ehxCl5-1YMfArDDki8',
    appId: '1:318003575454:android:0ad84c3bc808f34ca4598f',
    messagingSenderId: '318003575454',
    projectId: 'tipsyapp-c8bff',
    storageBucket: 'tipsyapp-c8bff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_fMQdDKwVc49rWuAlLySqJyi816DfV8s',
    appId: '1:318003575454:ios:02798a81e51560fda4598f',
    messagingSenderId: '318003575454',
    projectId: 'tipsyapp-c8bff',
    storageBucket: 'tipsyapp-c8bff.firebasestorage.app',
    iosBundleId: 'com.social.flutterTipsy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_fMQdDKwVc49rWuAlLySqJyi816DfV8s',
    appId: '1:318003575454:ios:02798a81e51560fda4598f',
    messagingSenderId: '318003575454',
    projectId: 'tipsyapp-c8bff',
    storageBucket: 'tipsyapp-c8bff.firebasestorage.app',
    iosBundleId: 'com.social.flutterTipsy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjH-MgvnNyjOWAZbtK39NIDiJTby0vJrc',
    appId: '1:318003575454:web:5683d4c03f39530ba4598f',
    messagingSenderId: '318003575454',
    projectId: 'tipsyapp-c8bff',
    authDomain: 'tipsyapp-c8bff.firebaseapp.com',
    storageBucket: 'tipsyapp-c8bff.firebasestorage.app',
    measurementId: 'G-RP81Q27R5D',
  );
}
